### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by f-liva** [GuyPaddock/wsl2-lando-docker-ce-equiv#1]
As object, thank you

**Comment by f-liva** [comment]
For noobs user like me:

sudo apt install equivs -y && \
git clone https://github.com/GuyPaddock/wsl2-lando-docker-ce-equiv && \
equivs-build wsl2-lando-docker-ce-equiv/docker-ce-dummy.ctl && \
sudo dpkg -i docker-ce-dummy_1.0_all.deb

**Comment by GuyPaddock** [comment]
Thanks, @f-liva! Those steps work if you want to build from source.

You can also download the binary deb package from [the Releases page](https://github.com/GuyPaddock/wsl2-lando-docker-ce-equiv/releases) and then use `dpkg -i <NAME OF FILE>.deb`. I recognize that requires trusting my releases, but I assure you that the only thing inside is the package descriptor and no binaries.

**Comment by f-liva** [comment]
Thanks for the suggestion!
